import { Inter } from "next/font/google";
import "./globals.css";
import FreeShipping from "./components/freeShipping";
import Header from "./components/header";
import Collections from "./components/collections";
import Footer from "./components/footer";

// ✅ Importing Inter font with all weight variants
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // ✅ All weights included
});

export const metadata = {
  title: "Shaad Fabrics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <FreeShipping />
        <Header />
        <Collections />
        {children}
        <Footer />
      </body>
    </html>
  );
}
